pipeline {
  agent none
  stages {
    stage('SCM CHECKOUT') {
      agent any        
      steps {
        git branch: 'main', url: 'https://github.com/PradeepNandam/Jenkins-Zero-To-Hero'
      }
    }
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('DB') {
      agent {
        docker { image 'mysql:latest' }
      }
      steps {
        sh 'mysql --version'
      }
    }
  }
}
